export default {
  id: "charm-hyper",
  priority: 65,
  hasFree: true,
  alias: "charm-hyper",
  display: {
    name: "Charm Hyper",
    icon: "bolt",
    color: "#7C3AED",
    textIcon: "CH",
    website: "https://hyper.charm.land",
    notice: {
      apiKeyUrl: "https://hyper.charm.land",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://hyper.charm.land/v1/chat/completions",
    validateUrl: "https://hyper.charm.land/v1/models",
  },
  models: [
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "gemma-4-26b-a4b-it", name: "Gemma 4 26B A4B" },
    { id: "glm-5", name: "GLM-5" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5.2", name: "GLM-5.2" },
    { id: "gpt-oss-120b", name: "GPT-OSS 120B" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "llama-3.3-70b-instruct", name: "Llama 3.3 70B Instruct" },
    { id: "llama-4-maverick-17b-128e-instruct-fp8", name: "Llama 4 Maverick 17B 128E Instruct FP8" },
    { id: "minimax-m2.7", name: "MiniMax M2.7" },
    { id: "qwen3.6-flash", name: "Qwen3.6-Flash" },
    { id: "qwen3.6-max", name: "Qwen3.6-Max" },
    { id: "qwen3.6-plus", name: "Qwen3.6-Plus" },
    { id: "qwen3.7-max", name: "Qwen3.7-Max" },
    { id: "qwen3.7-plus", name: "Qwen3.7-Plus" },
    { id: "qwen3-coder-480b-a35b-instruct-int4-mixed-ar", name: "Qwen3 Coder 480B A35B Instruct INT4 Mixed AR" },
    { id: "qwen3-next-80b-a3b-instruct", name: "Qwen3 Next 80B A3B Instruct" },
  ],
};
