// Regression: distinct API keys must never merge in usage stats (masked-prefix
// collision), and raw API keys must never appear anywhere in the serialized
// stats object (JSON property names included). See upstream issue.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, it, expect, beforeAll, afterAll } from "vitest";

const originalDataDir = process.env.DATA_DIR;
let tempDir;
let db;
let adapter;

// All three share the first 8 chars ("sk-same0"), like real keys generated by
// one installation (sk-{machineId}-{keyId}-{crc8} → first 8 chars identical).
const KEY_A = "sk-same0-user-a-secret";
const KEY_B = "sk-same0-user-b-secret";
const KEY_DELETED = "sk-same0-deleted-key-xyz";
const ALL_KEYS = [KEY_A, KEY_B, KEY_DELETED];

// Timestamps: recent enough for 24h, and clamped past local midnight so the
// "today" branch sees them even when the suite runs just after 00:00.
const startOfDay = new Date();
startOfDay.setHours(0, 0, 0, 0);
const base = Math.max(Date.now() - 120_000, startOfDay.getTime() + 1_000);
const ts = (i) => new Date(base + i * 1000).toISOString();

const TS_A = ts(0);
const TS_B = ts(40);
const TS_A_OTHER_MODEL = ts(10);
const TS_A_OTHER_PROVIDER = ts(20);
const TS_DELETED = ts(30);
const TS_NO_KEY = ts(35);

function insertHistory(row) {
  adapter.run(
    `INSERT INTO usageHistory(timestamp, provider, model, connectionId, apiKey, endpoint, promptTokens, completionTokens, cost, status, tokens, meta) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      row.timestamp, row.provider, row.model, null, row.apiKey ?? null, "chat",
      row.promptTokens, row.completionTokens, row.cost, "ok",
      JSON.stringify({ prompt_tokens: row.promptTokens, completion_tokens: row.completionTokens }),
      "{}",
    ]
  );
}

function namedGroups(stats, model) {
  return Object.values(stats.byApiKey).filter(
    (e) => e.rawModel === model && ["User A", "User B"].includes(e.keyName)
  );
}

beforeAll(async () => {
  tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "9router-akgroup-"));
  process.env.DATA_DIR = tempDir;
  db = await import("@/lib/db/index.js");
  await db.initDb();
  const { getAdapter } = await import("@/lib/db/driver.js");
  adapter = await getAdapter();

  const now = new Date().toISOString();
  // apiKeys rows for the two known keys (raw SQL — createApiKey() generates
  // its own key value, so it cannot register a chosen fixture key).
  adapter.run(
    `INSERT INTO apiKeys(id, key, name, machineId, isActive, createdAt) VALUES(?, ?, ?, ?, ?, ?)`,
    ["fixture-id-a", KEY_A, "User A", "machine0fixture0", 1, now]
  );
  adapter.run(
    `INSERT INTO apiKeys(id, key, name, machineId, isActive, createdAt) VALUES(?, ?, ?, ?, ?, ?)`,
    ["fixture-id-b", KEY_B, "User B", "machine0fixture0", 1, now]
  );

  // Live-window rows (raw SQL — saveRequestUsage() would overwrite cost via
  // pricing lookup, zeroing it for these fake providers).
  insertHistory({ timestamp: TS_A, provider: "test-provider", model: "test-model", apiKey: KEY_A, promptTokens: 10, completionTokens: 2, cost: 0.01 });
  insertHistory({ timestamp: TS_B, provider: "test-provider", model: "test-model", apiKey: KEY_B, promptTokens: 20, completionTokens: 4, cost: 0.02 });
  insertHistory({ timestamp: TS_A_OTHER_MODEL, provider: "test-provider", model: "other-model", apiKey: KEY_A, promptTokens: 5, completionTokens: 1, cost: 0.005 });
  insertHistory({ timestamp: TS_A_OTHER_PROVIDER, provider: "other-provider", model: "test-model", apiKey: KEY_A, promptTokens: 7, completionTokens: 3, cost: 0.007 });
  insertHistory({ timestamp: TS_DELETED, provider: "test-provider", model: "test-model", apiKey: KEY_DELETED, promptTokens: 1, completionTokens: 1, cost: 0.001 });
  insertHistory({ timestamp: TS_NO_KEY, provider: "test-provider", model: "test-model", apiKey: null, promptTokens: 3, completionTokens: 2, cost: 0.003 });

  // A usageDaily row in the PERSISTED LEGACY FORMAT (compound keys containing
  // the full raw keys + meta.apiKey) — exactly the shape real deployments
  // have on disk. Proves read-compat AND the leak fix on historical data.
  const y = new Date(Date.now() - 86400000);
  const dateKey = `${y.getFullYear()}-${String(y.getMonth() + 1).padStart(2, "0")}-${String(y.getDate()).padStart(2, "0")}`;
  const counters = (requests, promptTokens, completionTokens, cost) =>
    ({ requests, promptTokens, completionTokens, cachedTokens: 0, cost });
  const day = {
    requests: 2, promptTokens: 30, completionTokens: 6, cachedTokens: 0, cost: 0.03,
    byProvider: { "test-provider": counters(2, 30, 6, 0.03) },
    byModel: { "test-model|test-provider": { ...counters(2, 30, 6, 0.03), rawModel: "test-model", provider: "test-provider" } },
    byAccount: {},
    byApiKey: {
      [`${KEY_A}|test-model|test-provider`]: { ...counters(1, 10, 2, 0.01), rawModel: "test-model", provider: "test-provider", apiKey: KEY_A },
      [`${KEY_B}|test-model|test-provider`]: { ...counters(1, 20, 4, 0.02), rawModel: "test-model", provider: "test-provider", apiKey: KEY_B },
    },
    byEndpoint: {},
  };
  adapter.run(`INSERT INTO usageDaily(dateKey, data) VALUES(?, ?)`, [dateKey, JSON.stringify(day)]);
});

afterAll(() => {
  if (tempDir) fs.rmSync(tempDir, { recursive: true, force: true });
  if (originalDataDir === undefined) delete process.env.DATA_DIR;
  else process.env.DATA_DIR = originalDataDir;
});

describe("API-key grouping: live branch (today / 24h)", () => {
  it.each(["today", "24h"])("keeps same-prefix keys distinct for %s", async (period) => {
    const stats = await db.getUsageStats(period);
    const groups = namedGroups(stats, "test-model").filter((e) => e.provider === "test-provider");
    expect(groups).toHaveLength(2);
    const byName = Object.fromEntries(groups.map((g) => [g.keyName, g]));
    expect(byName["User A"].requests).toBe(1);
    expect(byName["User A"].promptTokens).toBe(10);
    expect(byName["User A"].completionTokens).toBe(2);
    expect(byName["User A"].cost).toBeCloseTo(0.01);
    expect(byName["User B"].requests).toBe(1);
    expect(byName["User B"].promptTokens).toBe(20);
    expect(byName["User B"].completionTokens).toBe(4);
    expect(byName["User B"].cost).toBeCloseTo(0.02);
    expect(stats.totalRequests).toBe(6);
  });

  it("keeps different models in separate groups", async () => {
    const stats = await db.getUsageStats("24h");
    const otherModel = namedGroups(stats, "other-model");
    expect(otherModel).toHaveLength(1);
    expect(otherModel[0].keyName).toBe("User A");
    expect(otherModel[0].requests).toBe(1);
    expect(otherModel[0].promptTokens).toBe(5);
  });

  it("keeps different providers in separate groups", async () => {
    const stats = await db.getUsageStats("24h");
    const otherProvider = namedGroups(stats, "test-model").filter((e) => e.provider === "other-provider");
    expect(otherProvider).toHaveLength(1);
    expect(otherProvider[0].keyName).toBe("User A");
    expect(otherProvider[0].requests).toBe(1);
    expect(otherProvider[0].promptTokens).toBe(7);
  });

  it("attributes lastUsed per key, not per collided bucket", async () => {
    const stats = await db.getUsageStats("24h");
    const byName = Object.fromEntries(
      namedGroups(stats, "test-model").filter((e) => e.provider === "test-provider").map((g) => [g.keyName, g])
    );
    expect(byName["User A"].lastUsed).toBe(TS_A);
    expect(byName["User B"].lastUsed).toBe(TS_B);
  });

  it("gives deleted/unknown keys a distinct group with a distinguishing name", async () => {
    const stats = await db.getUsageStats("24h");
    const deleted = Object.values(stats.byApiKey).filter(
      (e) => e.rawModel === "test-model" && /^sk-same0\*\*\*#[0-9a-f]{6}$/.test(e.keyName)
    );
    expect(deleted).toHaveLength(1);
    expect(deleted[0].requests).toBe(1);
    expect(deleted[0].promptTokens).toBe(1);
    expect(deleted[0].apiKeyKey).toMatch(/^k:[0-9a-f]{16}$/);
  });

  it("keeps no-key traffic under the sentinel, compound-keyed like the daily path", async () => {
    const stats = await db.getUsageStats("24h");
    const entry = stats.byApiKey["local-no-key|test-model|test-provider"];
    expect(entry).toBeDefined();
    expect(entry.keyName).toBe("Local (No API Key)");
    expect(entry.apiKeyKey).toBe("local-no-key");
    expect(entry.requests).toBe(1);
    expect(entry.promptTokens).toBe(3);
  });
});

describe("API-key grouping: aggregate branch (7d, legacy persisted data)", () => {
  it("reconstructs distinct groups from raw-key legacy usageDaily records", async () => {
    const stats = await db.getUsageStats("7d");
    const groups = namedGroups(stats, "test-model").filter((e) => e.provider === "test-provider");
    expect(groups).toHaveLength(2);
    const byName = Object.fromEntries(groups.map((g) => [g.keyName, g]));
    expect(byName["User A"].requests).toBe(1);
    expect(byName["User A"].promptTokens).toBe(10);
    expect(byName["User B"].requests).toBe(1);
    expect(byName["User B"].promptTokens).toBe(20);
  });

  it("overlays precise per-key lastUsed timestamps from history", async () => {
    const stats = await db.getUsageStats("7d");
    const byName = Object.fromEntries(
      namedGroups(stats, "test-model").filter((e) => e.provider === "test-provider").map((g) => [g.keyName, g])
    );
    expect(byName["User A"].lastUsed).toBe(TS_A);
    expect(byName["User B"].lastUsed).toBe(TS_B);
  });
});

describe("raw-key leak prevention", () => {
  it.each(["today", "24h", "7d", "all"])("serializes no raw API key for %s", async (period) => {
    const stats = await db.getUsageStats(period);
    const serialized = JSON.stringify(stats);
    for (const key of ALL_KEYS) {
      expect(serialized).not.toContain(key);
    }
    for (const objKey of Object.keys(stats.byApiKey)) {
      for (const key of ALL_KEYS) {
        expect(objKey).not.toContain(key);
      }
    }
  });

  it("persists a per-install identity salt in _meta", async () => {
    await db.getUsageStats("24h");
    const row = adapter.get(`SELECT value FROM _meta WHERE key = 'usageIdentitySalt'`);
    expect(row?.value).toMatch(/^[0-9a-f]{32}$/);
  });

  it("produces stable identities across calls (same byApiKey keys)", async () => {
    const first = await db.getUsageStats("24h");
    const second = await db.getUsageStats("24h");
    expect(Object.keys(second.byApiKey).sort()).toEqual(Object.keys(first.byApiKey).sort());
  });
});
