import { PROVIDERS } from "../config/providers.js";
import { proxyAwareFetch } from "../utils/proxyFetch.js";
import { markFreebuffPoolFailure } from "./freebuffProxyFitness.js";
import { observeActivePoolFitness } from "../services/proxyPoolFitness.js";
import { fetchWithNetworkRetry, sessionCacheKey } from "./freebuffTransport.js";

export const SESSION_STALE_CODES = new Set([428, 409, 410]);
const STATE = (globalThis.__9routerFreebuffState__ ??= { sessionCache: new Map(), inflight: new Map(), modelLockCooldowns: new Map(), poolLimitCooldowns: new Map() });
const { sessionCache, inflight, modelLockCooldowns, poolLimitCooldowns } = STATE;
const origin = () => new URL(PROVIDERS.freebuff.baseUrl).origin;
const cooldown = (map, key) => { const entry = map.get(key); const until = entry?.until || entry; if (until && until > Date.now()) return entry; map.delete(key); return null; };
const proxyKey = (proxyOptions) => proxyOptions?.vercelRelayUrl || proxyOptions?.connectionProxyUrl || "direct";
const safeStatus = (error) => { try { return error?.status; } catch { return undefined; } };
function gate(code, message, currentModel) { if (code === "model_locked") return { kind: "model_locked", currentModel }; if (code === "session_model_mismatch") return /limited/i.test(String(message || "")) ? { kind: "limited_ip" } : { kind: "model_locked", currentModel }; return { kind: "stale" }; }
export function gateFromText(text) { try { const data = JSON.parse(String(text || "")); return gate(data.error || data.error_type || data.status || "", data.message || "", data.currentModel || null); } catch { return { kind: "stale" }; } }
function gateFromError(error) { try { const text = String(error); const index = text.indexOf("{"); return index < 0 ? null : gateFromText(text.slice(index)); } catch { return null; } }
export async function requestSession(token, model, proxyOptions) {
  const response = await fetchWithNetworkRetry(`${origin()}/api/v1/freebuff/session`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, "User-Agent": "codebuff-cli/0.0.138", "x-freebuff-model": model } }, proxyOptions);
  const data = await response.json().catch(() => ({}));
  if (response.status === 401) throw Object.assign(new Error("Freebuff session auth failed (401) — re-login in the dashboard"), { status: 401 });
  if (!response.ok) throw Object.assign(new Error(`Freebuff session request failed: ${response.status}`), { status: response.status });
  if (data.status === "active") { const expiresAt = Date.parse(data.expiresAt || ""); sessionCache.set(sessionCacheKey(token, model), { instanceId: data.instanceId, expiresAt: Number.isFinite(expiresAt) ? expiresAt : Date.now() + 3_600_000 }); return { instanceId: data.instanceId, status: "active" }; }
  if (data.status === "none") return { instanceId: null, status: "none" };
  throw new Error(`${data.message || "Freebuff session rejected"} ${JSON.stringify({ error: data.status || "unknown", message: data.message || "", currentModel: data.currentModel || null })}`);
}
export async function ensureSession(token, model, proxyOptions, force = false) { const key = sessionCacheKey(token, model); const cached = sessionCache.get(key); if (!force && cached?.expiresAt > Date.now()) return { instanceId: cached.instanceId, status: "active" }; if (force) { sessionCache.delete(key); inflight.delete(key); return requestSession(token, model, proxyOptions); } if (!inflight.has(key)) inflight.set(key, requestSession(token, model, proxyOptions).finally(() => inflight.delete(key))); return inflight.get(key); }
export async function startRun(token, proxyOptions, agentId) { const response = await fetchWithNetworkRetry(`${origin()}/api/v1/agent-runs`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, "User-Agent": "codebuff-cli/0.0.138" }, body: JSON.stringify({ action: "START", agentId, ancestorRunIds: [] }) }, proxyOptions); const text = await response.text().catch(() => ""); let data = {}; try { data = JSON.parse(text); } catch {} if (response.status === 401) throw Object.assign(new Error("Freebuff run auth failed (401) — re-login in the dashboard"), { status: 401 }); if (!response.ok || !data.runId) throw Object.assign(new Error(`Freebuff run start failed: ${response.status}`), { status: response.status }); return data.runId; }
export async function finishRun(token, runId, status, proxyOptions) { if (!runId) return; try { await proxyAwareFetch(`${origin()}/api/v1/agent-runs`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ action: "FINISH", runId, status }), signal: AbortSignal.timeout(10_000) }, proxyOptions); } catch {} }
export async function preflight(token, model, proxyOptions, poolId) { const locked = cooldown(modelLockCooldowns, `${token}::${model}`); if (locked) throw Object.assign(new Error("Freebuff session locked to another model"), { status: 409, resetsAtMs: locked.until || locked }); const key = `${proxyKey(proxyOptions)}::${model}`; const local = cooldown(poolLimitCooldowns, key); if (!local || !poolId) return; const fitness = await observeActivePoolFitness(poolId, `freebuff::${model}`); if (fitness === null) { poolLimitCooldowns.delete(key); return; } const error = Object.assign(new Error(`Freebuff limited-mode IP rejected ${model}`), { status: 409 }); error.poolScoped = { poolId, scope: `freebuff::${model}`, reason: "limited_ip", fitnessVersion: fitness?.version || local.version, until: fitness?.until || local.until }; throw error; }
export function sessionFailureHandler({ token, model, proxyOptions, log }) { return async (error, signal) => { const sessionGate = gateFromError(error); if (sessionGate?.kind === "model_locked") { const until = Date.now() + 600_000; modelLockCooldowns.set(`${token}::${model}`, until); throw Object.assign(new Error(`Freebuff session is locked to ${sessionGate.currentModel ? `"${sessionGate.currentModel}"` : "another model"}`), { status: 409, resetsAtMs: until }); } if (sessionGate?.kind === "limited_ip") { const poolScoped = await markFreebuffPoolFailure({ model, proxyOptions, stage: "session_acquire", status: 409, error: "limited_ip", provenance: "relay_internal" }); if (poolScoped?.fitnessVersion) poolLimitCooldowns.set(`${proxyKey(proxyOptions)}::${model}`, { until: poolScoped.until, version: poolScoped.fitnessVersion }); const limited = Object.assign(new Error(`Freebuff limited-mode IP rejected ${model}`), { status: 409 }); if (poolScoped) limited.poolScoped = poolScoped; log?.warn?.("AUTH", "Freebuff limited IP"); throw limited; } const status = safeStatus(error); const poolScoped = await markFreebuffPoolFailure({ model, proxyOptions, stage: "session_acquire", error, status, provenance: Number.isInteger(status) ? "target_response" : undefined, signal }); if (poolScoped && error && typeof error === "object") error.poolScoped = poolScoped; throw error; }; }
export function clearPoolLimitedCooldown(model, proxyOptions) { poolLimitCooldowns.delete(`${proxyKey(proxyOptions)}::${model}`); }
export function resetSessionCache() { sessionCache.clear(); inflight.clear(); modelLockCooldowns.clear(); poolLimitCooldowns.clear(); }
export function sessionStateSize() { return { sessions: sessionCache.size, inflight: inflight.size, modelLocks: modelLockCooldowns.size, poolLimits: poolLimitCooldowns.size }; }
export function pruneSessionState(now = Date.now()) { let removed = 0; for (const map of [sessionCache, modelLockCooldowns, poolLimitCooldowns]) for (const [key, entry] of map) if ((entry?.expiresAt || entry?.until || entry) <= now) { map.delete(key); removed += 1; } return removed; }
